version: "3"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=StrongPassword00
    ports:
      - '1433:1433'
    volumes:
      - mssql-data:/var/opt/mssql/data
  php-apache:
    image: php:apache
    depends_on:
      - mssql
    ports:
      - '80:80'
    volumes:
      - ../backend:/var/www/html
volumes:
  mssql-data: